development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: db/production
  Host: ec2-34-194-158-176.compute-1.amazonaws.com
  Database: dfcqu8oo86qep
  User: dtzpbeqmqfbjsh
  Port: 5432
  Password: afa0ee5b89c135d7cd4d5983e0d44295278c618562233b86464207e8d92457d2
