development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: db/production
  Host: ec2-44-207-133-100.compute-1.amazonaws.com
  Database: ddin3a00pe2akn
  User: phpdjlgxdvzzvt
  Port: 5432
  Password: 3fe3656c073ec249b856bf697e4fdfb78a58c65843c18cf3324e510c84df372a
